spring.application.name=api-gateway-service
server.port=8000

#define static routes for product service application
spring.cloud.gateway.routes[0].id=management-department-service
spring.cloud.gateway.routes[0].uri=http://localhost:8002
spring.cloud.gateway.routes[0].predicates[0]=Path=/student/**,/academic-staff/**,/non-academic-staff/**

#define static routes for product service application
spring.cloud.gateway.routes[1].id=technology-department-service
spring.cloud.gateway.routes[1].uri=http://localhost:8003
spring.cloud.gateway.routes[1].predicates[0]=Path=/tech-student/**,/tech-academic-staff/**,/tech-non-academic-staff/**

#define static routes for product service application
spring.cloud.gateway.routes[2].id=technology-department-service
spring.cloud.gateway.routes[2].uri=http://localhost:8001
spring.cloud.gateway.routes[2].predicates[0]=Path=/applied-student/**,/applied-academic-staff/**,/applied-non-academic-staff/**

#define static routes for product service application
spring.cloud.gateway.routes[3].id=admin-service
spring.cloud.gateway.routes[3].uri=http://localhost:8004
spring.cloud.gateway.routes[3].predicates[0]=Path=/admin/**

